version: '3'

volumes:
  db-data:

networks:
  quizlet-clone:
    name: quizlet-clone
    driver: bridge

services:
  api:
    build:
      context: .
      args:
        ENV_NAME: ${ENV_NAME:-development}
    image: api
    entrypoint: ['yarn', 'start:${ENV_NAME:-development}']
    container_name: api
    env_file:
      - .env.${ENV_NAME:-development}
    ports:
      - '8080:8080'
    # restart: always
    depends_on:
      - mongo
    networks:
      - quizlet-clone
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    # restart: always
    env_file:
      - .env.${ENV_NAME:-development}
    volumes:
      - db-data:/data/db
    networks:
      - quizlet-clone
