version: '3'

volumes:
  db-data:

networks:
  quizlet-clone:
    name: quizlet-clone
    driver: bridge

services:
  api:
    # build: .
    # image: api
    image: siorjik/nest-image:latest
    container_name: api
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLIENT_HOST=${CLIENT_HOST}
      - DB_URL=${DB_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    # env_file:
    #   - ${ENV_FILE:-.env.development}
    ports:
      - '8080:8080'
    # restart: always
    depends_on:
      - mongo
    networks:
      - quizlet-clone
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    # restart: always
    # env_file:
    #   - ${ENV_FILE:-.env.development}
    volumes:
      - db-data:/data/db
    networks:
      - quizlet-clone
